services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livrocaixa
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    restart: always
    networks:
      - livrocaixa_network
    environment:
      PGSQL_HOST: postgres
      PGSQL_PORT: 5432
      PGSQL_USER: admin
      PGSQL_PASSWORD: senha@123
      PGSQL_DB_NAME: livrocaixa

  postgres:
    image: postgres:15
    container_name: livrocaixadb
    environment:
      POSTGRES_DB: livrocaixa
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha@123
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - livrocaixa_network

networks:
  livrocaixa_network:
    driver: bridge
